package com.stuffwithstuff.bantam

/**
 * A simple token class. These are generated by Lexer and consumed by Parser.
 */
class Token(val type: TokenType, val text: String) {
    override fun toString(): String {
        return text
    }

}